package acceptance

import (
	"encoding/json"
	"fmt"
	"slices"
	"strings"
)

// The two rendered forms of a report, both committed beside this package so a
// reviewer reads the same verdict the gate produced.
const (
	// ReportJSON is the machine-readable report.
	ReportJSON = "report.json"
	// ReportMarkdown is the reviewer-readable report.
	ReportMarkdown = "report.md"
)

// JSON renders the report as the committed machine-readable artifact:
// two-space indent, newline-terminated, and byte-identical for an identical
// checkout.
func (r Report) JSON() ([]byte, error) {
	raw, err := json.MarshalIndent(r, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("acceptance: render the report: %w", err)
	}
	return append(raw, '\n'), nil
}

// Markdown renders the report as the reviewer-readable artifact: the verdict,
// what it obliges, then every clause in full so conformance can be audited one
// clause at a time.
func (r Report) Markdown() []byte {
	var b strings.Builder
	b.WriteString("# Greenfield acceptance gate\n\n")
	b.WriteString("Generated by `go test ./acceptance -run TestGate -update`. Do not edit by hand: the gate regenerates this file from the checkout and a stale copy fails its own test.\n\n")

	fmt.Fprintf(&b, "**Verdict: %s** — %d of %d clauses hold.\n\n", r.Verdict, r.Counts.Met, r.Counts.Clauses)
	fmt.Fprintf(&b, "**Forces pause:** %t\n\n", r.ForcesPause)
	fmt.Fprintf(&b, "**Action:** %s.\n\n", strings.TrimSuffix(r.Action, "."))

	b.WriteString("| Specification | Clauses | Met | Unmet |\n|---|---:|---:|---:|\n")
	for _, s := range sortedSources(r.BySource) {
		c := r.BySource[s]
		fmt.Fprintf(&b, "| %s | %d | %d | %d |\n", s, c.Clauses, c.Met, c.Unmet)
	}
	b.WriteString("\n")

	if unmet := r.Unmet(); len(unmet) > 0 {
		b.WriteString("## Clauses that do not hold\n\n")
		for _, c := range unmet {
			fmt.Fprintf(&b, "### %s\n\n", c.ID)
			fmt.Fprintf(&b, "- **Requires:** %s\n", c.Requires)
			fmt.Fprintf(&b, "- **Asserted:** %s\n", c.Asserts)
			for _, v := range c.Violations {
				fmt.Fprintf(&b, "- **Violation:** %s\n", v)
			}
			b.WriteString("\n")
		}
	}

	b.WriteString("## Open conditions\n\n")
	b.WriteString("Each is a live measurement over a real driven build. None can be settled by inspecting a checkout, so this gate holds the clause to its mechanism and records the measurement here for whatever drives the engine next.\n\n")
	for _, c := range r.OpenConditions {
		fmt.Fprintf(&b, "- **%s** — %s\n", c.Clause, c.Measurement)
	}
	b.WriteString("\n## Every clause\n\n")

	for _, s := range sortedSources(r.BySource) {
		fmt.Fprintf(&b, "### %s\n\n", s)
		b.WriteString("| Clause | Bar | Met | Requires | Asserted |\n|---|---|---|---|---|\n")
		for _, c := range r.Clauses {
			if c.Source != s {
				continue
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s |\n", c.ID, c.Bar, met(c.Met), cell(c.Requires), cell(c.Asserts))
		}
		b.WriteString("\n")
	}
	return []byte(b.String())
}

// met renders a clause outcome for a table cell.
func met(ok bool) string {
	if ok {
		return "yes"
	}
	return "**no**"
}

// cell escapes a sentence for a Markdown table cell, where an unescaped pipe
// would split the row.
func cell(s string) string { return strings.ReplaceAll(s, "|", `\|`) }

// sortedSources returns the report's specifications in a stable order.
func sortedSources(by map[Source]Counts) []Source {
	out := make([]Source, 0, len(by))
	for s := range by {
		out = append(out, s)
	}
	slices.Sort(out)
	return out
}
